### ISSUE TITLE
Firefox Invalid Date on Detailed Info

### ISSUE THREAD

**Issue by olkitu** [CellMapper/Map-BETA#1]
# Basic Info

* Browser Name and Version: Latest Firefox and Safari
* Operating System: Windows 10

# Current behavior

Show's First seen and Last seen date: Invalid Date

# Expected behavior

Should show Date Time value.

# Video/Screenshot link (optional)

![image](https://user-images.githubusercontent.com/10426342/28390775-1d9a5860-6ce4-11e7-91d4-6a24422d384e.png)

**Comment by jessenic** [comment]
Done.
