### ISSUE TITLE
Modal provider selection dialog cannot be clicked away from to get it off the screen

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#10]
# Basic Info
No.

# Steps to reproduce
Click "select provider"
click ANYWHERE ELSE on map except the dialog/button
# Current behavior
Dialog just sits there
# Expected behavior
I want to go back to the map, make the dialog go away.

# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
Done, will be live later today.
