### ISSUE TITLE
The background map is completely gone

### ISSUE THREAD

**Issue by el-emka** [CellMapper/Map-BETA#21]
# Basic Info

* Browser Name and Version: Chrome 50
* Operating System: Windows 10
* Same issue on other systems and browsers (Linux, Android, Firefox)

# Steps to reproduce

Open the beta map with any background map

# Current behavior

The background map is missing

# Expected behavior

The background map is visible

# Video/Screenshot link (optional)

![image](https://user-images.githubusercontent.com/2356683/64852626-06051180-d61a-11e9-9bc2-d8eb33be2563.png)

**Comment by jessenic** [comment]
Bing Maps has stopped working, please use this link until we remove Bing Maps from the testmap:
https://www.cellmapper.net/testmap/osmap
