### ISSUE TITLE
MCC Code selection VERY unintuitive.

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#3]
# Basic Info

Google Chrome	58.0.3029.110 (Official Build) (64-bit)
Revision	691bdb490962d4e6ae7f25c6ab1fdd0faaf19cd0-refs/branch-heads/3029@{#830}
OS	Linux
JavaScript	V8 5.8.283.38
Flash	26.0.0.137 /home/mike/.config/google-chrome/PepperFlash/26.0.0.137/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --flag-switches-begin --flag-switches-end

# Steps to reproduce
Load cellmapper.net/testmap/

# Current behavior
Site appears to automagically geolocate, and pre-select MCC 310 for USA.
I wish to change to 311 for Verizon
Unable to click on checkbox for 311 while 310 is selected
Forced to click on 310 again to de-select before being able to select 311

# Expected behavior
Just clicking on 311 should switch to 311. It doesnt.
If you're going to have the ability for "multiple" networks filtered at the same time, yet not "multiple" MCCs, fix the selection logic to not require a forced deselection and instead simply allow a new selection to usurp/replace the current one. 

# Video/Screenshot link (optional)
Can do later.

**Comment by jessenic** [comment]
This is a known issue and will be fixed soon.

**Comment by brycenesbitt** [comment]
Many many users won't know what to select (LTE, CDMA, GSM, HDSPA).  And they probably have a multiband phone anyway.  How about a default of "all bands", and a later filter for given bands?

**Comment by olkitu** [comment]
@brycenesbitt  I think that make more confusing because not easy show all on same map and too much data same map. Also future it will show also 2G GSM, 3G UMTS, 4G LTE so i hope people understand generations what provider also use. 

Too many markers on map = confusing

**Comment by brycenesbitt** [comment]
@olkitu when a new user comes to the map, the big question is "is this even worth it?.  "Do they have enough data"?  Since most phones are multi band, the most relevant map may well be a blended map (all bands in one color of course).

**Comment by jessenic** [comment]
MCC selection has been changed. Also added a new landing page that combines all MCCs into one: https://www.cellmapper.net/testmap/

**Comment by brycenesbitt** [comment]
Where is that new landing page?

Is there a way to build a page showing all bands of a given carrier (e.g.
show Tmobile GSM+UMTS+LTE on one map)?
