### ISSUE TITLE
When dragging map to exact point, removal of finger from mousebutton causes map to "jump" further in the direction dragged

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#4]
# Basic Info

Google Chrome	58.0.3029.110 (Official Build) (64-bit)
Revision	691bdb490962d4e6ae7f25c6ab1fdd0faaf19cd0-refs/branch-heads/3029@{#830}
OS	Linux
JavaScript	V8 5.8.283.38
Flash	26.0.0.137 /home/mike/.config/google-chrome/PepperFlash/26.0.0.137/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --flag-switches-begin --flag-switches-end

# Steps to reproduce
Click on the map
Drag map
Make sure your mouse is 100% stable, and not moving
Remove finger from mouse button

# Current behavior
Map, from a standstill, jumps more in the direction it was going. 

# Expected behavior
Map stays still.
# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
This seems to be a Leaflet issue, I see you reported it at Leaflet/Leaflet#5652 already.

**Comment by jessenic** [comment]
Will get fixed when Leaflet 1.3.0 is released.
