### ISSUE TITLE
Brief detail popup useless - blocks tower coverage blob until user interaction to remove it

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#5]
# Basic Info
Chrome 58/linux
Gah i dont want to keep pasting from About:

# Steps to reproduce
Click on a tower
# Current behavior
Stupid useless popup appears with no good information whatsoever on it
Popup covers coverage pattern blobs equating to more clicking to remove popup to see coverage.

# Expected behavior
The left sidebar appearing with actual sector information - IE the action of "more info" should be DEFAULT because "informational" popup is useless.

# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
The popup was added with mobile users in mind. More info is a bit problematic on phones as it covers the whole page. Maybe this could be a user option in the future linked to the user profile.

**Comment by jessenic** [comment]
Tower coverage is now shown when hovering with mouse. To make it stay on the map, tower can be clicked and the popup can be dismissed by closing it.
