### ISSUE TITLE
Sector color all the same color "blue" ; should be different colors like Android app

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#6]
# Basic Info
Chrome 58/linux

# Steps to reproduce
Click on tower to view coverage pattern blobs
# Current behavior
All blue
# Expected behavior
Multicolor so that each blob can be easier distinguished
Mirror the exact strategy used in the Android app. Please....

# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
Duplicate of #2, will be implemented.
