### ISSUE TITLE
Clicking tower icon again fails to remove coverage blobs from view

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#7]
# Basic Info
Chrome 58/Linux
# Steps to reproduce
Click a tower
Potentially click somewhere else to remove the useless info popup
Click it again
# Current behavior
Blue tower blobs stay visible
# Expected behavior
Blue tower blobs go away
# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
This is by design, as people would click the tower marker twice and not see the sectors come up. Sector coverage can be removed by clicking the sectors. Maybe they could go away when clicked on the map?

**Comment by jessenic** [comment]
Clicking the coverage polygons will remove them now. Right clicking them will remove only the one clicked.
