### ISSUE TITLE
Grouped towers - no option to ungroup

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#8]
# Basic Info
Chrome 58/Linux

# Steps to reproduce
Zoom out 
# Current behavior
Towers are grouped without a selection to ungroup them
# Expected behavior
Option available to ungroup 
# Video/Screenshot link (optional)

**Comment by olkitu** [comment]
Map is on BETA and not yet have all same feature as old map have. We working filters on settings on map.

**Comment by jessenic** [comment]
Added option to ungroup in filters, only for higher zoom levels to not hang browsers..
