### ISSUE TITLE
Grouped towers - Clicking zooms fully and instead of enumerating clickable tower icons at distance

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#9]
# Basic Info
Chrome 58/linux

# Steps to reproduce
Click on a grouped tower symbol (2) or (3) or even more

# Current behavior
Zooms as close as possible to the map, very annoyingly
# Expected behavior
Multiple different tower icons populate at the clicked point, to be individually clicked, same as the old version of the map

# Video/Screenshot link (optional)

**Comment by jessenic** [comment]
Made this more intelligent, it is now more similar to the old map. If a cluster has all the towers inside 100 meters, it will not zoom but expand. Also made the clustering less aggressive on lower zoom levels.
